# Generated by Django 3.2.6 on 2022-05-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_patrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='face_encoding',
        ),
    ]
